# golangci-lint configuration for version 2.x
# See https://golangci-lint.run/usage/configuration/ for full options

version: 2

run:
  timeout: 5m
  skip-dirs:
    - vendor
  tests: true

output:
  formats:
    colored-line-number: stdout
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - gocritic
    - revive
    - nolintlint
    - bodyclose
    - rowserrcheck
    - whitespace
    - goprintffuncname

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  dupl:
    threshold: 100
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: package-comments
      - name: var-naming
      - name: error-strings
      - name: error-return
      - name: error-naming
      - name: indent-error-flow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
